//! Parity tests: compare Rust vivisect output against Python golden files.
//!
//! Golden files are generated by fixtures/generate_golden.py using
//! the Python vivisect implementation.

use serde::Deserialize;
use std::collections::HashMap;
use std::path::Path;
use vivisect::constants::Architecture;
use vivisect::core::workspace::VivWorkspace;
use vivisect::parsers::PeParser;

// ============================================================================
// Golden file structures
// ============================================================================

#[derive(Deserialize, Debug)]
struct GoldenOutput {
    source: String,
    file: String,
    metadata: GoldenMetadata,
    segments: Vec<GoldenSegment>,
    imports: Vec<GoldenImport>,
    exports: Vec<GoldenExport>,
    functions: Vec<GoldenFunction>,
    function_count: usize,
    codeblock_count: usize,
    xref_count: usize,
    string_count: usize,
    location_counts: HashMap<String, usize>,
    #[serde(default)]
    disassembly_sample: Vec<GoldenDisasmFunction>,
}

#[derive(Deserialize, Debug)]
struct GoldenMetadata {
    architecture: String,
    platform: String,
    format: String,
    bigend: bool,
    entry_points: Vec<u64>,
    base_address: u64,
    pointer_size: u64,
}

#[derive(Deserialize, Debug)]
struct GoldenSegment {
    va: u64,
    size: usize,
    perms: u64,
    name: String,
}

#[derive(Deserialize, Debug)]
struct GoldenImport {
    va: u64,
    name: String,
}

#[derive(Deserialize, Debug)]
struct GoldenExport {
    va: u64,
    #[serde(rename = "type")]
    export_type: u64,
    name: String,
    filename: String,
}

#[derive(Deserialize, Debug)]
struct GoldenFunction {
    va: u64,
    name: String,
    size: u64,
    block_count: usize,
}

#[derive(Deserialize, Debug)]
struct GoldenDisasmFunction {
    function_va: u64,
    function_name: String,
    instructions: Vec<GoldenInstruction>,
}

#[derive(Deserialize, Debug)]
struct GoldenInstruction {
    va: u64,
    size: usize,
    mnem: String,
    #[serde(default)]
    is_call: bool,
    #[serde(default)]
    is_branch: bool,
    #[serde(default)]
    is_return: bool,
    #[serde(default)]
    falls_through: bool,
    #[serde(default)]
    operand_count: usize,
}

// ============================================================================
// Helper functions
// ============================================================================

fn load_golden(name: &str) -> Option<GoldenOutput> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("fixtures")
        .join(name);
    if !path.exists() {
        eprintln!("Golden file not found: {}", path.display());
        return None;
    }
    let data = std::fs::read_to_string(&path).unwrap();
    Some(serde_json::from_str(&data).unwrap())
}

fn sample_path(name: &str) -> std::path::PathBuf {
    Path::new(r"C:\Users\yeti-sec\Desktop\floss_test_samples").join(name)
}

// ============================================================================
// PE Parsing Parity Tests
// ============================================================================

#[test]
fn parity_conti_pe32_format_detection() {
    let path = sample_path("floss_conti");
    if !path.exists() {
        eprintln!("Test sample not found, skipping");
        return;
    }

    let format = vivisect::parsers::detect_format(&path).unwrap();
    assert_eq!(format, vivisect::parsers::BinaryFormat::Pe);
}

#[test]
fn parity_conti_pe32_architecture() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let pe = PeParser::load(&path).unwrap();
    let rust_arch = pe.architecture();

    assert_eq!(golden.metadata.architecture, "i386");
    assert_eq!(rust_arch, Architecture::I386, "Architecture mismatch");
}

#[test]
fn parity_conti_pe32_entry_point() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let pe = PeParser::load(&path).unwrap();
    let rust_entry = pe.entry_point();

    // The primary entry point (first one) must match
    let python_primary_ep = golden.metadata.entry_points[0];
    assert_eq!(
        rust_entry, python_primary_ep,
        "Primary entry point mismatch: Rust={:#x} Python={:#x}",
        rust_entry, python_primary_ep
    );
}

#[test]
fn parity_conti_pe32_section_count() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let pe = PeParser::load(&path).unwrap();
    let rust_sections = pe.sections();

    // Python has 5 segments (includes PE header), Rust has 4 (sections only)
    // The actual PE sections should match (excluding Python's header segment)
    let python_section_count = golden.segments.iter()
        .filter(|s| s.va != golden.metadata.entry_points[0] / 0x1000 * 0x1000 - 0x1000)
        .count();

    // Rust should have the PE sections
    assert!(
        rust_sections.len() >= 4,
        "Expected at least 4 sections, got {}",
        rust_sections.len()
    );
}

#[test]
fn parity_conti_pe32_section_addresses() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let pe = PeParser::load(&path).unwrap();
    let rust_sections = pe.sections();

    // Compare section VAs (skip Python's header segment at image base)
    let python_sections: Vec<&GoldenSegment> = golden.segments.iter()
        .filter(|s| s.va != 0x400000)  // skip header segment
        .collect();

    for ps in &python_sections {
        let matching = rust_sections.iter().find(|rs| rs.virtual_address == ps.va);
        assert!(
            matching.is_some(),
            "Python section at {:#x} ({}) not found in Rust output",
            ps.va, ps.name
        );
    }
}

#[test]
fn parity_conti_pe32_import_count() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let pe = PeParser::load(&path).unwrap();
    let rust_imports = pe.imports();

    assert_eq!(
        rust_imports.len(),
        golden.imports.len(),
        "Import count mismatch: Rust={} Python={}",
        rust_imports.len(),
        golden.imports.len()
    );
}

#[test]
fn parity_conti_pe32_import_names() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let pe = PeParser::load(&path).unwrap();
    let rust_imports = pe.imports();

    // Extract just function names from both sides for comparison
    // Python format: "kernel32.CloseHandle_0042e000" -> extract "CloseHandle"
    // Rust format: library="KERNEL32.dll", name="CloseHandle"
    let mut python_names: Vec<String> = golden.imports.iter()
        .map(|i| {
            // Extract function name from "library.FuncName_addr" format
            let parts: Vec<&str> = i.name.split('.').collect();
            if parts.len() >= 2 {
                // Remove trailing _addr suffix
                let func_part = parts[1];
                if let Some(idx) = func_part.rfind('_') {
                    // Check if suffix is a hex address
                    let suffix = &func_part[idx+1..];
                    if suffix.chars().all(|c| c.is_ascii_hexdigit()) && suffix.len() >= 6 {
                        return func_part[..idx].to_string();
                    }
                }
                func_part.to_string()
            } else {
                i.name.clone()
            }
        })
        .collect();

    let mut rust_names: Vec<String> = rust_imports.iter()
        .map(|i| i.name.clone())
        .collect();

    python_names.sort();
    rust_names.sort();

    // Check that all Python import names appear in Rust
    let mut missing = Vec::new();
    for pn in &python_names {
        if !rust_names.iter().any(|rn| rn == pn || rn.contains(pn.as_str())) {
            missing.push(pn.clone());
        }
    }

    assert!(
        missing.len() <= 5,  // Allow some tolerance for naming differences
        "Too many missing import names ({}/{}): {:?}",
        missing.len(), python_names.len(), &missing[..missing.len().min(10)]
    );
}

// ============================================================================
// Workspace Analysis Parity Tests
// ============================================================================

#[test]
fn parity_conti_pe32_workspace_load() {
    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let mut ws = VivWorkspace::new();
    let result = ws.load_from_file(&path);
    assert!(result.is_ok(), "Failed to load PE32: {:?}", result.err());
    assert_eq!(ws.architecture(), Architecture::I386);
}

#[test]
fn parity_conti_pe32_analysis_functions() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let mut ws = VivWorkspace::new();
    ws.load_from_file(&path).unwrap();

    // Run analysis
    let result = ws.analyze();

    let rust_funcs = ws.get_functions();
    let python_func_count = golden.function_count;

    eprintln!("=== Function Discovery Parity ===");
    eprintln!("  Python functions: {}", python_func_count);
    eprintln!("  Rust functions:   {}", rust_funcs.len());
    eprintln!("  Analysis stats:   {:?}", result.total);
    if !result.failures.is_empty() {
        eprintln!("  Failures: {:?}", result.failures);
    }

    // Report parity ratio
    let ratio = rust_funcs.len() as f64 / python_func_count as f64;
    eprintln!("  Parity ratio: {:.1}%", ratio * 100.0);

    // Check overlap with Python function addresses
    let python_func_vas: std::collections::HashSet<u64> = golden.functions.iter()
        .map(|f| f.va)
        .collect();
    let rust_func_vas: std::collections::HashSet<u64> = rust_funcs.iter().copied().collect();

    let overlap = python_func_vas.intersection(&rust_func_vas).count();
    eprintln!("  Address overlap:  {} functions found by both", overlap);

    let rust_only: Vec<u64> = rust_func_vas.difference(&python_func_vas)
        .copied().collect();
    eprintln!("  Rust-only:        {} functions", rust_only.len());
    if !rust_only.is_empty() {
        eprintln!("    First 10: {:?}", rust_only.iter().take(10).map(|v| format!("{:#x}", v)).collect::<Vec<_>>());
    }

    let python_only_count = python_func_vas.difference(&rust_func_vas).count();
    eprintln!("  Python-only:      {} functions", python_only_count);

    // This test documents the current gap rather than asserting equality
    // As the Rust port improves, tighten this threshold
    assert!(
        rust_funcs.len() > 0,
        "Rust analysis discovered ZERO functions — code flow analysis is broken"
    );
}

// ============================================================================
// Disassembly Flag Parity Tests
// ============================================================================

#[test]
fn parity_conti_pe32_disasm_flags() {
    let golden = match load_golden("golden_conti_pe32.json") {
        Some(g) => g,
        None => return,
    };

    let path = sample_path("floss_conti");
    if !path.exists() { return; }

    let mut ws = VivWorkspace::new();
    ws.load_from_file(&path).unwrap();

    use vivisect::envi::archs::{X86Disassembler, X86Mode};
    use vivisect::envi::ArchitectureModule;

    let disasm = X86Disassembler::new(X86Mode::Mode32);

    let mut total = 0;
    let mut mnem_match = 0;
    let mut size_match = 0;
    let mut call_match = 0;
    let mut branch_match = 0;
    let mut ret_match = 0;

    for func in &golden.disassembly_sample {
        for py_insn in &func.instructions {
            let bytes = match ws.read_memory(py_insn.va, 16) {
                Ok(b) => b,
                Err(_) => continue,
            };

            let rust_op = match disasm.disassemble(&bytes, py_insn.va) {
                Ok(o) => o,
                Err(_) => continue,
            };

            total += 1;

            if rust_op.mnem == py_insn.mnem {
                mnem_match += 1;
            } else {
                eprintln!(
                    "  MNEM MISMATCH at {:#x}: Python='{}' Rust='{}'",
                    py_insn.va, py_insn.mnem, rust_op.mnem
                );
            }

            if rust_op.size as usize == py_insn.size {
                size_match += 1;
            } else {
                eprintln!(
                    "  SIZE MISMATCH at {:#x}: Python={} Rust={}",
                    py_insn.va, py_insn.size, rust_op.size
                );
            }

            if rust_op.is_call() == py_insn.is_call {
                call_match += 1;
            } else {
                eprintln!(
                    "  CALL FLAG MISMATCH at {:#x} '{}': Python={} Rust={}",
                    py_insn.va, py_insn.mnem, py_insn.is_call, rust_op.is_call()
                );
            }

            let rust_is_branch = rust_op.is_branch();
            if rust_is_branch == py_insn.is_branch {
                branch_match += 1;
            } else {
                eprintln!(
                    "  BRANCH FLAG MISMATCH at {:#x} '{}': Python={} Rust={}",
                    py_insn.va, py_insn.mnem, py_insn.is_branch, rust_is_branch
                );
            }

            if rust_op.is_return() == py_insn.is_return {
                ret_match += 1;
            } else {
                eprintln!(
                    "  RET FLAG MISMATCH at {:#x} '{}': Python={} Rust={}",
                    py_insn.va, py_insn.mnem, py_insn.is_return, rust_op.is_return()
                );
            }
        }
    }

    eprintln!("\n=== Disassembly Flag Parity ===");
    eprintln!("  Total instructions compared: {}", total);
    eprintln!("  Mnemonic match:  {}/{} ({:.1}%)", mnem_match, total, mnem_match as f64 / total as f64 * 100.0);
    eprintln!("  Size match:      {}/{} ({:.1}%)", size_match, total, size_match as f64 / total as f64 * 100.0);
    eprintln!("  Call flag match: {}/{} ({:.1}%)", call_match, total, call_match as f64 / total as f64 * 100.0);
    eprintln!("  Branch flag:     {}/{} ({:.1}%)", branch_match, total, branch_match as f64 / total as f64 * 100.0);
    eprintln!("  Return flag:     {}/{} ({:.1}%)", ret_match, total, ret_match as f64 / total as f64 * 100.0);

    // Assert high parity on critical flags.
    // Mnemonic threshold is 90% because iced-x86 uses Intel canonical names
    // (je/jne/jb/jae) while Python vivisect uses AT&T aliases (jz/jnz/jc/jnc).
    // These are semantically identical — same opcode, different display name.
    assert!(
        mnem_match as f64 / total as f64 > 0.90,
        "Mnemonic parity below 90%: {}/{} (synonym differences expected: jnz/jne, jz/je, jc/jb, jnc/jae)",
        mnem_match, total
    );
    assert!(
        size_match as f64 / total as f64 > 0.95,
        "Size parity below 95%: {}/{}",
        size_match, total
    );
    assert!(
        call_match as f64 / total as f64 > 0.90,
        "Call flag parity below 90%: {}/{}",
        call_match, total
    );
}
